config/routes.rb
Rails.application.routes.draw do
  resources :foods
  resources :posts
  root 'logins#login'
  get 'home/top'
  get 'home/calendar_index'
  get 'logins/login'
  post 'logins/login_check'
  post 'logins/logout'
  get 'entries/serect_date_entry'

  

  post  'home/update', to: 'home#update', as: 'home_update'

  resources :entries
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/entry.rb
class Entry < ApplicationRecord
  validate :error_check
  def error_check
    if user_id.blank?
      errors[:base] << 'ユーザーIDは必ず入力してください。'
    elsif day.present?
      entry_check = Entry.find_by(user_id: user_id, day: day)
      if entry_check.present?
        errors[:base] << 'その日のデータは、すでに登録済みです。'
      end
    end
    if weight.blank?
      errors[:base] << '体重は必ず入力してください。'
    end
    if height.blank?
      errors[:base] << '身長は必ず入力してください。'
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new(user_id: session[:user_id])
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    params[:entry][:day] = params[:day]
    cal_check = { "ヨガ" => 100, "ランニング" => 240, "ウォーキング" => 60, "サイクリング" => 160, "縄跳び" => 300, "入浴" => 87, "掃除" => 100, "足踏み" => 80, "TV体操" => 120, "バレー" => 120, "テニス" => 210, "水泳" => 180, "バドミントン" => 200, "ゴルフ" => 100 }
    cal_check_time = { "30分" => 1, "1時間" => 2, "1時間30分" => 3, "2時間" => 4, "2時間30分" => 5, "3時間" => 6}
    if params[:entry][:ex_type_1].present?
      params[:entry][:ex_amount_1] = cal_check[params[:entry][:ex_type_1]] * cal_check_time[params[:entry][:ex_time_1]]
    end
    if params[:entry][:ex_type_2].present?
      params[:entry][:ex_amount_2] = cal_check[params[:entry][:ex_type_2]] * cal_check_time[params[:entry][:ex_time_2]]
    end
    if params[:entry][:ex_type_3].present?
      params[:entry][:ex_amount_3] = cal_check[params[:entry][:ex_type_3]] * cal_check_time[params[:entry][:ex_time_3]]
    end

    @entry = Entry.new(entry_params)
    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    params[:entry][:day] = params[:day]
    cal_check = { "ヨガ" => 100, "ランニング" => 240, "ウォーキング" => 60, "サイクリング" => 160, "縄跳び" => 300, "入浴" => 87, "掃除" => 100, "足踏み" => 80, "TV体操" => 120, "バレー" => 120, "テニス" => 210, "水泳" => 180, "バドミントン" => 200, "ゴルフ" => 100 }
    cal_check_time = { "30分" => 1, "1時間" => 2, "1時間30分" => 3, "2時間" => 4, "2時間30分" => 5, "3時間" => 6}
    if params[:entry][:ex_type_1].present?
      params[:entry][:ex_amount_1] = cal_check[params[:entry][:ex_type_1]] * cal_check_time[params[:entry][:ex_time_1]]
    end
    if params[:entry][:ex_type_2].present?
      params[:entry][:ex_amount_2] = cal_check[params[:entry][:ex_type_2]] * cal_check_time[params[:entry][:ex_time_2]]
    end
    if params[:entry][:ex_type_3].present?
      params[:entry][:ex_amount_3] = cal_check[params[:entry][:ex_type_3]] * cal_check_time[params[:entry][:ex_time_3]]
    end

    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def serect_date_entry
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:user_id, :weight, :height, :ex_type_1, :ex_time_1, :ex_amount_1, :ex_type_2, :ex_time_2, :ex_amount_2, :ex_type_3, :ex_time_3, :ex_amount_3, :meal_asa, :meal_hiru, :meal_ban, :snack, :snack_memo, :condition, :day, :memo)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
        <ul>
          <% entry.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
    </div>
  <% end %>

<table>
    <tr>
      <div class="field">
        <th><%= form.label :ユーザーID %></th>
        <td><%= form.text_field :user_id, id: :entry_user_id, readonly: true %></td>
      </div>
    </tr>

  <tr>
    <div class="field" style="text-align: center;">
      <th><%= form.label :体重 %></th>
      <td><%= form.number_field :weight, id: :entry_weight %></td>
    </div>
  </tr>

  <tr>
    <div class="field" style="text-align: center;">
      <th><%= form.label :身長 %></th>
      <td><%= form.number_field :height, id: :entry_height %></td>
    </div>
  </tr>

  <tr>
    <div class="field">
      <th><%= form.label :運動種類 %></th>
      <td><%= form.select :ex_type_1,[["ヨガ","ヨガ"],["ランニング","ランニング"],["ウォーキング","ウォーキング"],["サイクリング","サイクリング"],["縄跳び","縄跳び"],["入浴","入浴"],["掃除","掃除"],["足踏み","足踏み"],["TV体操","TV体操"],["バレー","バレー"],["テニス","テニス"],["水泳","水泳"],["バドミントン","バドミントン"],["ゴルフ","ゴルフ"]],include_blank: "運動種類１" %></td>
      <td><%= form.select :ex_type_2,[["ヨガ","ヨガ"],["ランニング","ランニング"],["ウォーキング","ウォーキング"],["サイクリング","サイクリング"],["縄跳び","縄跳び"],["入浴","入浴"],["掃除","掃除"],["足踏み","足踏み"],["TV体操","TV体操"],["バレー","バレー"],["テニス","テニス"],["水泳","水泳"],["バドミントン","バドミントン"],["ゴルフ","ゴルフ"]],include_blank: "運動種類２" %></td>
      <td><%= form.select :ex_type_3,[["ヨガ","ヨガ"],["ランニング","ランニング"],["ウォーキング","ウォーキング"],["サイクリング","サイクリング"],["縄跳び","縄跳び"],["入浴","入浴"],["掃除","掃除"],["足踏み","足踏み"],["TV体操","TV体操"],["バレー","バレー"],["テニス","テニス"],["水泳","水泳"],["バドミントン","バドミントン"],["ゴルフ","ゴルフ"]],include_blank: "運動種類３" %></td>
    </div>
  </tr>

  <tr>
    <div class="field">
      <th><%= form.label :運動時間 %></th>
      <td><%= form.select :ex_time_1,[["30分","30分"],["1時間","1時間"],["1時間30分","1時間30分"],["2時間","2時間"],["2時間30分","2時間30分"],["3時間","3時間"]],include_blank: "運動時間１" %></td>
      <td><%= form.select :ex_time_2,[["30分","30分"],["1時間","1時間"],["1時間30分","1時間30分"],["2時間","2時間"],["2時間30分","2時間30分"],["3時間","3時間"]],include_blank: "運動時間２" %></td>
      <td><%= form.select :ex_time_3,[["30分","30分"],["1時間","1時間"],["1時間30分","1時間30分"],["2時間","2時間"],["2時間30分","2時間30分"],["3時間","3時間"]],include_blank: "運動時間３" %></td>
    </div>
  </tr>


  <div class="field">
    <tr>
      <th>食事</th>
      <td><%= form.label :朝食 %><%= form.check_box :meal_asa, id: :entry_meal_asa %></td>
      <td><%= form.label :昼食 %><%= form.check_box :meal_hiru, id: :entry_meal_hiru %></td>
      <td><%= form.label :夕食 %><%= form.check_box :meal_ban, id: :entry_meal_ban %></td>
      <td><%= form.label :間食 %><%= form.check_box :snack, id: :entry_snack %></td>
    </tr>
  </div>



  <tr>
    <div class="field">
      <th><%= form.label :食べたもの %></th>
      <td><%= form.text_area :snack_memo, id: :entry_snack_memo %></td>
    </div>
  </tr>

  <tr>
    <div class="field">
      <th><%= form.label :体調 %></th>
      <td><label><%= form.radio_button :condition, 0 %> 良い </label></td>
      <td><label><%= form.radio_button :condition, 1 %> ふつう </label></td>
      <td><label><%= form.radio_button :condition, 2 %> 悪い </label></td>
    </div>
  </tr>

  <tr>
    <div class="field">
      <th><%= form.label :日付 %></th>
      <td><%= date_field_tag :day, id: :entry_day %></td>
    </div>
  </tr>

  <tr>
    <div class="field">
      <th><%= form.label :メモ %></th>
      <td><%= form.text_area :memo, id: :entry_memo %></td>
    </div>
  </tr>
</table>

  <div class="actions">
    <%= form.submit '新規登録', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>変更画面</h1>

<%= render 'form', entry: @entry %>
<%= link_to '詳細', @entry %> 
<%= link_to '戻る', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>登録画面</h1>

<table>
  <thead>
    <tr>
      <th>ユーザーID</th>
      <th>体重</th>
      <th>身長</th>
      <th>運動種類</th>
      <th>運動時間</th>
      <th>カロリー</th>
      <th>運動種類</th>
      <th>運動時間</th>
      <th>カロリー</th>
      <th>運動種類</th>
      <th>運動時間</th>
      <th>カロリー</th>
      <th>朝食</th>
      <th>昼食</th>
      <th>晩食</th>
      <th>間食</th>
      <th>食べたもの</th>
      <th>体調</th>
      <th>日付</th>
      <th>メモ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.user_id %></td>
        <td><%= entry.weight %></td>
        <td><%= entry.height %></td>
        <td><%= entry.ex_type_1 %></td>
        <td><%= entry.ex_time_1 %></td>
        <td><%= entry.ex_amount_1 %>kcal</td>
        <td><%= entry.ex_type_2 %></td>
        <td><%= entry.ex_time_2 %></td>
        <td><%= entry.ex_amount_2 %>kcal</td>
        <td><%= entry.ex_type_3 %></td>
        <td><%= entry.ex_time_3 %></td>
        <td><%= entry.ex_amount_3 %>kcal</td>
        <td>
          <% if (entry.meal_asa == true) %>
            〇
          <% else %>
            ✖
          <% end %>
        </td>
        <td>
          <% if (entry.meal_hiru == true) %>
            〇
          <% else %>
            ✖
          <% end %>
        </td>
        <td>
          <% if (entry.meal_ban == true) %>
            〇
          <% else %>
            ✖
          <% end %>
        </td>
        <td>
          <% if (entry.snack == true) %>
            〇
          <% else %>
            ✖
          <% end %>
        </td>
        <td><%= entry.snack_memo %></td>
        <td>
          <% case entry.condition %>
            <% when 0 then %>
              良い
            <% when 1 then %>
              普通
            <% else %>
              悪い
            <% end %>
        </td>
        <td><%= entry.day %></td>
        <td><%= entry.memo %></td>
        <td><%= link_to '詳細', entry %></td>
        <td><%= link_to '変更', edit_entry_path(entry) %></td>
        <td><%= link_to '削除', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規登録', new_entry_path %>
<div>
  <%= link_to 'ホーム','home/top' %>
</div>

app/views/entries/new.html.erb
<h1>登録画面</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'ホーム', home_top_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ユーザーID:</strong>
  <%= @entry.user_id %>
</p>

<p>
  <strong>体重:</strong>
  <%= @entry.weight %>
</p>

<p>
  <strong>身長:</strong>
  <%= @entry.height %>
</p>

<p>
  <strong>運動種類:</strong>
  <%= @entry.ex_type_1 %>
</p>

<p>
  <strong>運動時間:</strong>
  <%= @entry.ex_time_1 %>
</p>

<p>
  <strong>カロリー:</strong>
  <%= @entry.ex_amount_1 %>kcal
</p>

<p>
  <strong>運動種類:</strong>
  <%= @entry.ex_type_2 %>
</p>

<p>
  <strong>運動時間:</strong>
  <%= @entry.ex_time_2 %>
</p>

<p>
  <strong>カロリー:</strong>
  <%= @entry.ex_amount_2 %>kcal
</p>

<p>
  <strong>運動種類:</strong>
  <%= @entry.ex_type_3 %>
</p>

<p>
  <strong>運動時間:</strong>
  <%= @entry.ex_time_3 %>
</p>

<p>
  <strong>カロリー:</strong>
  <%= @entry.ex_amount_3 %>kcal
</p>

<p>
  <strong>食事 朝:</strong>
  <% if (@entry.meal_asa == true) %>
    〇
  <% else %>
    ✖
  <% end %>
</p>

<p>
  <strong>食事 昼:</strong>
  <% if (@entry.meal_hiru == true) %>
    〇
  <% else %>
    ✖
  <% end %>
</p>

<p>
  <strong>食事 晩:</strong>
  <% if (@entry.meal_asa == true) %>
    〇
  <% else %>
    ✖
  <% end %>
</p>

<p>
  <strong>間食:</strong>
  <% if (@entry.snack == true) %>
    〇
  <% else %>
    ✖
  <% end %>
</p>

<p>
  <strong>食べたもの:</strong>
  <%= @entry.snack_memo %>
</p>

<p>
  <strong>体調:</strong>
  <% case @entry.condition %>
    <% when 0 then %>
      良い
    <% when 1 then %>
      普通
    <% else %>
      悪い
  <% end %>
</p>

<p>
  <strong>日付:</strong>
  <%= @entry.day %>
</p>

<p>
  <strong>メモ:</strong>
  <%= @entry.memo %>
</p>

<%= link_to '変更', edit_entry_path(@entry) %> |
<%= link_to '戻る', entries_path %> |