config/routes.rb
Rails.application.routes.draw do
  resources :foods
  resources :posts
  root 'logins#login'
  get 'home/top'
  get 'home/calendar_index'
  get 'logins/login'
  post 'logins/login_check'
  post 'logins/logout'
  get 'entries/serect_date_entry'

  

  post  'home/update', to: 'home#update', as: 'home_update'

  resources :entries
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @today = Date.today
    week = ['日','月','火','水','木','金','土']
    @yobi = week[@today.wday]
    entries = Entry.where(user_id: session[:user_id])
    period_h = {}

    if params[:period].blank?
      params[:period] = "week"
    end

    case params[:period]
    when "week" then
      now_week = Date.today.all_week
      begin_week = Date.today.beginning_of_week
      end_week = Date.today.end_of_week
      entries = entries.where('day >= ?', "#{begin_week}")
      entries = entries.where('day <= ?', "#{end_week}")
      now_week.each do |day|
        period_h.store(day.strftime('%Y-%m-%d'), "")
      end
    when "month" then
      now_month = Date.today.all_month
      begin_month = Date.today.beginning_of_month
      end_month = Date.today.end_of_month
      entries = entries.where('day >= ?', "#{begin_month}")
      entries = entries.where('day <= ?', "#{end_month}")
      now_month.each do |day|
        period_h.store(day.strftime('%Y-%m-%d'), "")
      end
    when "3month" then
      now_threemonth = Date.today.beginning_of_month.prev_month(3)
      end_month = Date.today.end_of_month
      entries = entries.where('day >= ?', "#{now_threemonth}")
      entries = entries.where('day <= ?', "#{end_month}")
      (now_threemonth..end_month).each do |day|
        period_h.store(day.strftime('%Y-%m-%d'), "")
      end
    when "6month" then
      now_sixmonth = Date.today.beginning_of_month.prev_month(6)
      end_month = Date.today.end_of_month
      entries = entries.where('day >= ?', "#{now_sixmonth}")
      entries = entries.where('day <= ?', "#{end_month}")
      (now_sixmonth..end_month).each do |day|
        period_h.store(day.strftime('%Y-%m-%d'), "")
      end
    end
    @user_id = session[:user_id]
    @authority = session[:authority]

    @data = []

    entries.each do |entry|
      period_h[entry.day.strftime('%Y-%m-%d')] = entry.weight
    end

    # ハッシュを配列に変換
    @data = period_h.to_a

    logger.debug("==================")
    logger.debug(@data)

    @entry_day = Entry.find_by(user_id: @user_id, day: @today)
  end

  def calendar_index
    calendar_day = params[:calendar_day]
    # カレンダーの月を変更して、日付を選んだ場合
    if params[:start_date].present?
      session[:start_date] = params[:start_date]
    else
      session[:start_date] = Date.today.strftime('%Y-%m-%d')
    end
    if calendar_day
      @entry = Entry.find_by(user_id: session[:user_id], day: calendar_day.to_date)
    else
      @entry = nil
    end
  end

  def update
    calendar_day = params[:calendar_day]
    entry = Entry.find_by(user_id: session[:user_id] , day: calendar_day.to_date)
    results = { :message => entry }
    #render partial: 'ajax_partial', locals: { :results => results }
    redirect_to home_calendar_index_path(calendar_day: params[:calendar_day], start_date: session[:start_date])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_ajax_partial.html.erb
Callback Msg = <%= results[:message].day %>

app/views/home/calendar_index.erb
<h1>カレンダー</h1>

<div class="container">
  <div class="sidebar_l">
    <div class="sidebar__item">
      <ul class="sidenav">
        <li><%= '動画' %>
          <ul>
            <li><%= link_to '筋トレ',posts_path(m_type: 1) %></li>
            <li><%= link_to 'ダイエット',posts_path(m_type: 2) %></li>
          </ul>
        </li>
        <li><%= '食べ物' %>
          <ul>
            <li><%= link_to '筋トレ',foods_path(ff_type: 1) %></li>
            <li><%= link_to 'ダイエット',foods_path(ff_type: 2) %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <main class="main">
    <%= month_calendar do |date| %>
      <% if date.sunday? %>
        <span style="color: red;"><%= date.day %></span>
      <% elsif date.saturday? %>
        <span style="color: blue;"><%= date.day %></span>
      <% else %>
        <%= date.day %>
      <% end %>
    <% end %>
  </main>
  <div class="sidebar">
    <div class="sidebar__item">
      <ul class="sidenav">
        <li><%= link_to '登録',new_entry_path %></li>
        <li><%= link_to '体重管理グラフ','top' %></li>
        <li><%= link_to '設定',users_path %></li>
      </ul>
    </div>
  </div>
</div>

<div class="memo">
  <% if @entry %>
    <table class="memo_entry">
      <tr>
        <th colspan="4"><%= @entry.day %></th>
      </tr>
      <tr>
        <td>体重  :<%= @entry.weight %>kg</td>
        <td>身長  :<%= @entry.height %>cm</td>
        <td>体調      :
          <% case @entry.condition %>
          <% when 0 then %>
              良い
          <% when 1 then %>
              普通
          <% else %>
              悪い
          <% end %>
        </td>
      </tr>
      <tr>
        <td>運動種類  :<%= @entry.ex_type_1 %></td>
        <td>運動時間  :<%= @entry.ex_time_1 %></td>
        <td>カロリー  :<%= @entry.ex_amount_1 %>kcal</td>
      </tr>
      <tr>
        <td>運動種類  :<%= @entry.ex_type_2 %></td>
        <td>運動時間  :<%= @entry.ex_time_2 %></td>
        <td>カロリー  :<%= @entry.ex_amount_2 %>kcal</td>
      </tr>
      <tr>
        <td>運動種類  :<%= @entry.ex_type_3 %></td>
        <td>運動時間  :<%= @entry.ex_time_3 %></td>
        <td>カロリー  :<%= @entry.ex_amount_3 %>kcal</td>
      </tr>
      <tr>
        <td>食事 朝   :<% if (@entry.meal_asa == true) %>
                          〇
                      <% else %>
                          ✖
                      <% end %>
        </td>
        <td>昼       :<% if (@entry.meal_hiru == true) %>
                          〇
                      <% else %>
                          ✖
                      <% end %>
        </td>
        <td>晩       :<% if (@entry.meal_asa == true) %>
                          〇
                      <% else %>
                          ✖
                      <% end %>
        </td>
        <td>間食      :<% if (@entry.snack == true) %>
                          〇
                      <% else %>
                          ✖
                      <% end %>
        </td>
      </tr>
      <tr>
        <td colspan="4">食べたもの :<%= @entry.snack_memo %></td>
      </tr>
      <tr>
        <td colspan="4">メモ :<%= @entry.memo %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/home/top.html.erb
<body>
<!-- Header Start -->
<!-- Header End -->

</body>

<table>
<center><h1><%= @today %> (<%= @yobi %>)</h1></center>

<nav class="period">
<div align="center">
  <ul>
    <li><%= link_to '週',home_top_path(period: "week") %></li>
    <li><%= link_to '月',home_top_path(period: "month") %></li>
    <li><%= link_to '3カ月',home_top_path(period: "3month") %></li>
    <li><%= link_to '6カ月',home_top_path(period: "6month") %></li>
  </ul>
</div>
</nav>

<div class="container">
  <div class="sidebar_l">
    <div class="sidebar_item">
      <ul class="sidenav">
        <li><%= '動画' %>
          <ul>
            <li><%= link_to '筋トレ',posts_path(m_type: 1) %></li>
            <li><%= link_to 'ダイエット',posts_path(m_type: 2) %></li>
          </ul>
        </li>
        <li><%= '食べ物' %>
          <ul>
            <li><%= link_to '筋トレ',foods_path(ff_type: 1) %></li>
            <li><%= link_to 'ダイエット',foods_path(ff_type: 2) %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <main class="main">
    <div class="data" style="float: left">
      <%= line_chart @data, width: "800px", height: "400px" %>
    </div>
  </main>
  <div class="sidebar">
    <div class="sidebar__item">
      <ul class="sidenav">
        <li><%= link_to '登録',new_entry_path %></li>
        <li><%= link_to '変更' ,entries_path %></li>
        <li><a href='calendar_index'>カレンダー</a></li>
      </ul>
    </div>
  </div>
</div>
</table>

app/views/home/video_index.erb
<h1>動画</h1>
<%= link_to 'ホーム','top' %>

<%= link_to '登録一覧',entries_path %>

<%= link_to '設定',users_path %>

<iframe width="560" height="315" src="https://www.youtube.com/embed/ZTjwBhjvXoc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>